MARGIN = 1

CAMERA_WIDTH = 80
CAMERA_HEIGHT = 50

PANEL_WIDTH = CAMERA_WIDTH
PANEL_HEIGHT = 5

SCREEN_WIDTH = CAMERA_WIDTH + MARGIN * 2
SCREEN_HEIGHT = CAMERA_HEIGHT + PANEL_HEIGHT + MARGIN * 4

CAMERA_X = MARGIN
CAMERA_Y = MARGIN

PANEL_X = CAMERA_X
PANEL_Y = CAMERA_Y + CAMERA_HEIGHT + MARGIN * 2
BAR_WIDTH = 16
MSG_X = PANEL_X + BAR_WIDTH + 2
MSG_WIDTH = PANEL_WIDTH - MSG_X
MSG_HEIGHT = PANEL_HEIGHT

LIMIT_FPS = 20

MAP_WIDTH = 40
MAP_HEIGHT = 40

BSP_MAP_DEPTH = 10
BSP_FULL_ROOMS = False
ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 6
MAX_ROOMS = 30
MAX_MONSTERS_PER_ROOM = 3

DIG_CORRIDORS = True
FOG_OF_WAR = True

FOV_ALG = 0  # libtcod.FOV_BASIC
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 10

PLAYER_SPEED = 2
DEFAULT_SPEED = 15
DEFAULT_ATTACK_SPEED = 20

STATE_PLAYING, STATE_PAUSE, STATE_DEAD = 0, 1, 2
ACTION_EXIT, ACTION_MOVE = 0, 1
