SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50

PANEL_HEIGHT = 5
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT
BAR_WIDTH = 16
MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - MSG_X
MSG_HEIGHT = PANEL_HEIGHT - 1

LIMIT_FPS = 20

CAMERA_WIDTH = SCREEN_WIDTH
CAMERA_HEIGHT = SCREEN_HEIGHT - PANEL_HEIGHT

MAP_WIDTH = CAMERA_WIDTH * 2
MAP_HEIGHT = CAMERA_HEIGHT * 2

ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 6
MAX_ROOMS = 30
MAX_MONSTERS_PER_ROOM = 3

FOV_ALG = 0  # libtcod.FOV_BASIC
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 10

PLAYER_SPEED = 2
DEFAULT_SPEED = 15
DEFAULT_ATTACK_SPEED = 20

STATE_PLAYING, STATE_PAUSE, STATE_DEAD = 0, 1, 2
ACTION_EXIT, ACTION_MOVE = 0, 1
